apiVersion: v1
kind: Service
metadata:
  name: scaletestapp
  namespace: default
  labels:
    app:
      scaletestapp
spec:
  selector:
    app: scaletestapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
      name: http
      appProtocol: http
  type: NodePort
